MESSAGE("Specialized FindPCRE Called")
if( NOT $ENV{PCRE_LIBRARY} STREQUAL "" )
  SET(PCRE_LIBRARY $ENV{PCRE_LIBRARY})

  if( NOT $ENV{PCRECPP_LIBRARY} STREQUAL "" )
  	SET(PCRECPP_LIBRARY $ENV{PCRECPP_LIBRARY})
  endif()


  set(PCRE_LIBRARIES ${PCRE_LIBRARY} ${PCRECPP_LIBRARY})

  if( NOT $ENV{PCRE_INCLUDE_DIR} STREQUAL "" )
     SET(PCRE_INCLUDE_DIR $ENV{PCRE_INCLUDE_DIR})
  endif()


  mark_as_advanced(PCRE_LIBRARY PCRE_INCLUDE_DIR)

  SET(PCRE_FOUND TRUE)

  MESSAGE("FindPCRE Set By Envionment")


endif()